[package]
name = "prism"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
prism-core = { path = "../prism-core" }
image = { version = "0.25.1", default-features = false, features = ["png"] }
