[workspace]
resolver = "2"
members = [
    "prism",
    "prism-core",
]

[workspace.package]
edition = "2021"
license = "MIT"
repository = "https://github.com/Mikayex/Prism"
version = "0.1.0"
authors = ["Thomas Laroche"]
