[package]
name = "prism-core"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
nalgebra = "0.32.5"
num-traits = "0.2.19"
